spring:
  application:
    name: open-certs
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/opencerts?authSource=admin

server:
  forward-headers-strategy: framework

application:
  import:
    api-key: ${APPLICATION_API_KEY}